version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-container
    environment:
      POSTGRES_DB: bookstore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kinto
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5433:5432"

  spring-app:
    image: bookstore-api:latest
    container_name: my-spring-app-container
    ports:
      - "8081:8081"
